export const GET_DEVELOPER_REQUEST = 'GET_DEVELOPER_REQUEST';
export const GET_DEVELOPER_SUCCESS = 'GET_DEVELOPER_REQUEST';
export const GET_DEVELOPER_FAIL = 'GET_DEVELOPER_FAIL';
export const SAVE_DEVELOPER = 'SAVE_DEVELOPER';

export const AUTH_REQUEST = 'AUTH_REQUEST';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const SAVE_DEVELOPER_ID = 'SAVE_DEVELOPER_ID';

export const GET_DEVELOPERS_REQUEST = 'GET_DEVELOPERS_REQUEST';
export const GET_DEVELOPERS_SUCCESS = 'GET_DEVELOPERS_SUCCESS';
export const GET_DEVELOPERS_FAIL = 'GET_DEVELOPERS_FAIL';
export const SAVE_DEVELOPERS = 'SAVE_DEVELOPERS';

export const SAVE_ADMIN_STATUS = 'SAVE_ADMIN_STATUS';

export const CREATE_DEVELOPER_REQUEST = 'CREATE_DEVELOPER_REQUEST';
export const CREATE_DEVELOPER_SUCCESS = 'CREATE_DEVELOPER_SUCCESS';
export const CREATE_DEVELOPER_FAIL = 'CREATE_DEVELOPER_FAIL';
