export const GET_DEVELOPER_REQUEST = 'GET_DEVELOPER_REQUEST';
export const GET_DEVELOPER_SUCCESS = 'GET_DEVELOPER_REQUEST';
export const GET_DEVELOPER_FAIL = 'GET_DEVELOPER_FAIL';
export const SAVE_DEVELOPER = 'SAVE_DEVELOPER';
