export const GET_DEVELOPER_REQUEST = 'GET_DEVELOPER_REQUEST';
export const GET_DEVELOPER_SUCCESS = 'GET_DEVELOPER_REQUEST';
export const GET_DEVELOPER_FAIL = 'GET_DEVELOPER_FAIL';
export const SAVE_DEVELOPER = 'SAVE_DEVELOPER';

export const AUTH_REQUEST = 'AUTH_REQUEST';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const SAVE_DEVELOPER_ID = 'SAVE_DEVELOPER_ID';
