export const GET_VIEWED_ISSUE_REQUEST = 'GET_VIEWED_ISSUE_REQUEST';
export const GET_VIEWED_ISSUE_SUCCESS = 'GET_VIEWED_ISSUE_SUCCESS';
export const GET_VIEWED_ISSUE_FAIL = 'GET_VIEWED_ISSUE_FAIL';
export const SAVE_VIEWED_ISSUE = 'SAVE_VIEWED_ISSUE';

export const CHANGE_ISSUE_REQUEST = 'CHANGE_ISSUE_REQUEST';
export const CHANGE_ISSUE_SUCCESS = 'CHANGE_ISSUE_SUCCESS';
export const CHANGE_ISSUE_FAIL = 'CHANGE_ISSUE_FAIL';

export const CREATE_ISSUE_REQUEST = 'CREATE_ISSUE_REQUEST';
export const CREATE_ISSUE_SUCCESS = 'CREATE_ISSUE_SUCCESS';
export const CREATE_ISSUE_FAIL = 'CREATE_ISSUE_FAIL';
