export const GET_VIEWED_STORY_REQUEST = 'GET_VIEWED_STORY_REQUEST';
export const GET_VIEWED_STORY_SUCCESS = 'GET_VIEWED_STORY_SUCCESS';
export const GET_VIEWED_STORY_FAIL = 'GET_VIEWED_STORY_FAIL';
export const SAVE_VIEWED_STORY = 'SAVE_VIEWED_STORY';

export const GET_STORIES_ISSUES_REQUEST = 'GET_STORIES_ISSUES_REQUEST';
export const GET_STORIES_ISSUES_SUCCESS = 'GET_STORIES_ISSUES_SUCCESS';
export const GET_STORIES_ISSUES_FAIL = 'GET_STORIES_ISSUES_FAIL';
export const SAVE_STORIES_ISSUES = 'SAVE_STORIES_ISSUES';

export const CHANGE_STORY_NAME_REQUEST = 'CHANGE_STORY_NAME_REQUEST';
export const CHANGE_STORY_NAME_SUCCESS = 'CHANGE_STORY_NAME_SUCCESS';
export const CHANGE_STORY_NAME_FAIL = 'CHANGE_STORY_NAME_FAIL';

export const CHANGE_STORY_DESCRIPTION_REQUEST = 'CHANGE_STORY_DESCRIPTION_REQUEST';
export const CHANGE_STORY_DESCRIPTION_SUCCESS = 'CHANGE_STORY_DESCRIPTION_SUCCESS';
export const CHANGE_STORY_DESCRIPTION_FAIL = 'CHANGE_STORY_DESCRIPTION_FAIL';
