export const GET_ALL_PROJECTS_REQUEST = 'GET_ALL_PROJECTS_REQUEST';
export const GET_ALL_PROJECTS_SUCCESS = 'GET_ALL_PROJECTS_SUCCESS';
export const GET_ALL_PROJECTS_FAIL = 'GET_ALL_PROJECTS_FAIL';
export const SAVE_ALL_PROJECTS = 'SAVE_ALL_PROJECTS';

export const GET_VIEWED_PROJECT_REQUEST = 'GET_VIEWED_PROJECT_REQUEST';
export const GET_VIEWED_PROJECT_SUCESS = 'GET_VIEWED_PROJECT_SUCCESS';
export const GET_VIEWED_PROJECT_FAIL = 'GET_VIEWED_PROJECT_FAIL';
export const SAVE_VIEWED_PROJECT = 'SAVE_VIEWED_PROJECT';

export const GET_PROJECT_BACKLOG_REQUEST = 'GET_PROJECT_BACKLOG_REQUEST';
export const GET_PROJECT_BACKLOG_SUCCESS = 'GET_PROJECT_BACKLOG_SUCCESS';
export const GET_PROJECT_BACKLOG_FAIL = 'GET_PROJECT_BACKLOG_FAIL';
export const SAVE_PROJECT_BACKLOG = 'SAVE_PROJECT_BACKLOG';

export const GET_PROJECT_ACTIVE_SPRINT_REQUEST = 'GET_PROJECT_ACTIVE_SPRINT_REQUEST';
export const GET_PROJECT_ACTIVE_SPRINT_SUCCESS = 'GET_PROJECT_ACTIVE_SPRINT_SUCCESS';
export const GET_PROJECT_ACTIVE_SPRINT_FAIL = 'GET_PROJECT_ACTIVE_SPRINT_FAIL';
export const SAVE_PROJECT_ACTIVE_SPRINT = 'SAVE_PROJECT_ACTIVE_SPRINT';
