export const GET_DEVELOPERS_WORKLOAD_REQUEST = 'GET_DEVELOPERS_WORKLOAD_REQUEST';
export const GET_DEVELOPERS_WORKLOAD_SUCCESS = 'GET_DEVELOPERS_WORKLOAD_SUCCESS';
export const GET_DEVELOPERS_WORKLOAD_FAIL = 'GET_DEVELOPERS_WORKLOAD_FAIL';
export const SAVE_DEVELOPERS_WORKLOAD = 'SAVE_DEVELOPERS_WORKLOAD';
