export const GET_DEVELOPERS_WORKLOAD_REQUEST = 'GET_DEVELOPERS_WORKLOAD_REQUEST';
export const GET_DEVELOPERS_WORKLOAD_SUCCESS = 'GET_DEVELOPERS_WORKLOAD_SUCCESS';
export const GET_DEVELOPERS_WORKLOAD_FAIL = 'GET_DEVELOPERS_WORKLOAD_FAIL';
export const SAVE_DEVELOPERS_WORKLOAD = 'SAVE_DEVELOPERS_WORKLOAD';

export const CREATE_WORKLOAD_REQUEST = 'CREATE_WORKLOAD_REQUEST';
export const CREATE_WORKLOAD_SUCCESS = 'CREATE_WORKLOAD_SUCCESS';
export const CREATE_WORKLOAD_FAIL = 'CREATE_WORKLOAD_FAIL';

export const DELETE_WORKLOAD_REQUEST = 'DELETE_WORKLOAD_REQUEST';
export const DELETE_WORKLOAD_SUCCESS = 'DELETE_WORKLOAD_SUCCESS';
export const DELETE_WORKLOAD_FAIL = 'DELETE_WORKLOAD_FAIL';
