export const GET_SPRINTS_STORIES_REQUEST = 'GET_SPRINTS_STORIES_REQUEST';
export const GET_SPRINTS_STORIES_SUCCESS = 'GET_SPRINTS_STORIES_SUCCESS';
export const GET_SPRINTS_STORIES_FAIL = 'GET_SPRINTS_STORIES_FAIL';
export const SAVE_SPRINTS_STORIES = 'SAVE_SPRINTS_STORIES';

export const CREATE_SPRINT_REQUEST = 'CREATE_SPRINT_REQUEST';
export const CREATE_SPRINT_SUCCESS = 'CREATE_SPRINT_SUCCESS';
export const CREATE_SPRINT_FAIL = 'CREATE_SPRINT_FAIL';

export const COMPLETE_SPRINT_REQUEST = 'COMPLETE_SPRINT_REQUEST';
export const COMPLETE_SPRINT_SUCCESS = 'COMPLETE_SPRINT_SUCCESS';
export const COMPLETE_SPRINT_FAIL = 'COMPLETE_SPRINT_FAIL';

export const GET_SPRINT_REQUEST = 'GET_SPRINT_REQUEST';
export const GET_SPRINT_SUCCESS = 'GET_SPRINT_SUCCESS';
export const GET_SPRINT_FAIL = 'GET_SPRINT_FAIL';

export const START_SPRINT_REQUEST = 'START_SPRINT_REQUEST';
export const START_SPRINT_SUCCESS = 'START_SPRINT_SUCCESS';
export const START_SPRINT_FAIL = 'START_SPRINT_FAIL';
