export const GET_SPRINTS_STORIES_REQUEST = 'GET_SPRINTS_STORIES_REQUEST';
export const GET_SPRINTS_STORIES_SUCCESS = 'GET_SPRINTS_STORIES_SUCCESS';
export const GET_SPRINTS_STORIES_FAIL = 'GET_SPRINTS_STORIES_FAIL';
export const SAVE_SPRINTS_STORIES = 'SAVE_SPRINTS_STORIES';
